pipeline:
  name: dec07Pipe
  identifier: dec07Pipe
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: f
        identifier: f
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait
                  identifier: Wait
                  spec:
                    duration: 10m
        tags: {}
